### ISSUE TITLE
Unable to connect to default Laravel 11 SQLite database

### ISSUE THREAD

**Issue by yaddly** [damms005/devdb-vscode#53] opened 2024-03-13 16:01 UTC
### Extension Version

1.4.0

### OS and Version

Windows 11 Pro 64-bit (10.0, Build 22631)

### VS Code Version

v1.87.2

### Database name and Version

SQLite v3.40.0

### Steps to reproduce

1. Create a new Laravel 11 app and attempt to connect to its default SQLite database.  I get the error below:

_Error: \\?\c:\Users\User_Account\.vscode\extensions\damms005.devdb-1.4.0-win32-x64\node_modules\sqlite3\build\Release\node_sqlite3.node is not a valid Win32 application. \\?\c:\Users\User_Account\.vscode\extensions\damms005.devdb-1.4.0-win32-x64\node_modules\sqlite3\build\Release\node_sqlite3.node_

4. I also tried to manually browse to the SQLite database location and select it but this too did not work. I got the errors below: 

_Provider selection error: Could not get database engine for file-picker-sqlite
The selected file is not a valid SQLite database._

### Expected behavior

I expected the devdb extension to automatically read the laravel configuration and connect to the dafault SQLite database

### Screenshots

![Screenshot 2024-03-13 175947](https://github.com/damms005/devdb-vscode/assets/8771294/e00972b1-245f-471d-afce-2947ba491da9)

**Comment by damms005** [comment] 2024-03-14 13:27
Duplicate of #46

**Closed by damms005** 2024-03-14 13:27 UTC
Labels: bug, duplicate, unconfirmed, low priority
